language: haskell

before_install:
  - cabal install hpc-coveralls
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test [optional-cabal-test-arguments]
after_script:
  - hpc-coveralls [your-test-suite-name]
